version: "3.9"

services:

  mongodb:
    image: mongo:7
    container_name: opsie-staging-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: opsie-staging-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/opsie_staging_db

  frontend:
    container_name: opsie-staging-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"

volumes:
  mongodb_data: