version: "3.9"

services:

  backend:
    container_name: opsie-staging-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - internal
      - opsie_proxy

  frontend:
    container_name: opsie-staging-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    networks:
      - internal
      - opsie_proxy

volumes:
  opsiewebsite_certbot_data:
    external: true

networks:
  internal:
  opsie_proxy:
    external: true