import { PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    PERMISSIONS.USER_VIEW_ME,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_VIEW_ACTIVE,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_UPDATE_PROFILE,
    PERMISSIONS.USER_RESET_PASSWORD,
    PERMISSIONS.USER_RESTORE,
    PERMISSIONS.USER_DELETE,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_VIEW_TIMELINE,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_DELETE
  ],

  manager: [
    PERMISSIONS.USER_VIEW_ME,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_VIEW_ACTIVE,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_UPDATE_PROFILE,
    PERMISSIONS.USER_RESET_PASSWORD,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_VIEW_TIMELINE,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_DELETE
  ],

  developer: [
    PERMISSIONS.USER_VIEW_ME,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_VIEW_ACTIVE,
    PERMISSIONS.USER_UPDATE_PROFILE,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_VIEW_TIMELINE,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_DELETE
  ],

  support: [
    PERMISSIONS.USER_VIEW_ME,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_VIEW_ACTIVE,
    PERMISSIONS.USER_UPDATE_PROFILE,

    PERMISSIONS.TICKET_VIEW,
    PERMISSIONS.TICKET_VIEW_TIMELINE,
    PERMISSIONS.TICKET_UPDATE,
  ]
};